[package]
name = "katutubo-app"
version = "0.1.0"
authors = ["ffimnsr <ffimnsr@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
yew = "0.17"
yew-router = "0.14"
log = "0.4"
wasm-logger = "0.2"
serde = "1"
serde_derive = "1"
wasm-bindgen = "0.2"
wee_alloc = "0.4"
